import React from 'react'
import useSWR from 'swr'
import { Loader } from './Loader';
import gsap from 'gsap';
import { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import axios from 'axios';

const Section = () => {
  const token = useRef(null);
  // EFFECT 
  useEffect(() => {
      var url = window.location;
      const token_ws = new URLSearchParams(url.search).get('token_ws');
      console.log("token: ", token_ws);
      token.current = token_ws
      console.log("This is my token now:", token.current);
      var post_url = 'https://chillin.cl/api/tokens'
      const datos = {token_ws}
      if (typeof token_ws !== 'undefined') 
        // the variable is defined
     {
        axios
      .post(post_url, datos)
      .then((resp) => {
      console.log("XDDD: ", resp);
      
      
      })
      .catch((err) => {
      console.log(err);
      });
      console.log("added!")
      }
      
      

    }, [])

  const [Turnon , setTurnon] = useState(true)
  const [Restaurante , setRestaurante] = useState(false)
  const [Profesionales , setProfesionales] = useState(false)
  const [Turismo, setTurismo] = useState(false)
    //FETCH GET negocios from api
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error } = useSWR('https://chillin.cl/api/negocios', fetcher);
  console.log("From section comp:", data);
  if (error)
    return (
      <div>
        <h1>404</h1>
        <p>Loading failed...</p>
      </div>
    );
  if (!data)
    return (
      <div>
       <Loader/>
      </div>
    );
      
  function eficAll() {
    setTurnon(true)
    setRestaurante(false)
    setProfesionales(false)
    setTurismo(false)
  }
  function eficR() {
    setTurnon(false)
    setRestaurante(true)
    setProfesionales(false)
    setTurismo(false)
  }
  function eficP() {
    setTurnon(false)
    setRestaurante(false)
    setProfesionales(true)
    setTurismo(false)
  }
  function eficT() {
    setTurnon(false)
    setRestaurante(false)
    setProfesionales(false)
    setTurismo(true)
  }

  


  return (
    <>
    <Head>
        <title>enCalbuco, Los Lagos, X Región</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ecfav.ico" />
      </Head>
  <h1 className="text-4xl font-bold text-center mt-16">Productos y Servicios</h1>
  <div className='mx-14 mt-10'>
    <button onClick={() => eficAll()} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Todos</button>
    <button onClick={() => eficR()} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Restaurante</button>
    <button onClick={() => eficP()} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Profesionales</button>
    <button onClick={() => eficT()} className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Turismo</button>
    </div>
    <div className=" grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-4 gap-4 mx-10 p-10">
    { 
      data.map((negocio) => {
        return (
        <div key={negocio.id} className={`${Turnon ? '':'hidden'} cursor-pointer rounded-lg shadow-lg pb-4 my-10 bg-white max-w-sm hover:bg-slate-200`}>
          <Link href="/negocios/[id]" as={`/negocios/${negocio.id}`}>
          <img className="rounded-t-lg object-cover max-h-64 w-full" src={`https://chillin.cl/${negocio.image}`} alt=""/></Link>
          <div className="p-6">
          <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.name}</h3>
          <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.cat_name}</h3>
          <h3 className="text-gray-900 text-lg font-medium mb-2 text-center">{negocio.description}</h3>
          </div>
        </div>
        )
      }) 
    }
        {
        data.filter((negocio) => negocio.cat_name=== "Profesionales").map((negocio) => {
          return(
          <div key={negocio.id} className={`${Profesionales ? '': 'hidden'} rounded-lg shadow-lg pb-4 my-10 bg-white max-w-sm hover:bg-slate-200`}>
            <Link href="/negocios/[id]" as={`/negocios/${negocio.id}`}>
           <img className="rounded-t-lg object-cover max-h-64 w-full" src={`https://chillin.cl/${negocio.image}`} alt=""/></Link>
            <div className="p-6">
              <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.name}</h3>
              <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.cat_name}</h3>
              <h3 className="text-gray-900 text-lg font-medium mb-2 text-center">{negocio.description}</h3>
            </div>
          </div>
          )
         }
        )}
        {
        data.filter((negocio) => negocio.cat_name=== "Restaurante").map((negocio) => {
          return(
            <div key={negocio.id} className={`${Restaurante ? '': 'hidden'} rounded-lg shadow-lg pb-4 my-10 bg-white max-w-sm hover:bg-slate-200`}>
              <Link href="/negocios/[id]" as={`/negocios/${negocio.id}`}>
           <img className="rounded-t-lg object-cover max-h-64 w-full" src={`https://chillin.cl/${negocio.image}`} alt=""/></Link>
            <div className="p-6">
              <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.name}</h3>
              <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.catName}</h3>
              <h3 className="text-gray-900 text-lg font-medium mb-2 text-center">{negocio.description}</h3>
            </div>
          </div>
            
          )
        }
        )
        }
        {data.filter((negocio) => negocio.cat_name=== "Turismo").map((negocio) => {
          return(
            <div key={negocio.id} className={`${Turismo ? '': 'hidden'} rounded-lg shadow-lg pb-4 my-10 bg-white max-w-sm hover:bg-slate-200`}>
              <Link href="/negocios/[id]" as={`/negocios/${negocio.id}`}>
              <img className="rounded-t-lg object-cover max-h-64 w-full" src={`https://chillin.cl/${negocio.image}`} alt=""/></Link>
              <div className="p-6">
                <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.name}</h3>
                <h3 className="text-gray-900 text-xl font-medium mb-2 text-center">{negocio.cat_name}</h3>
                <h3 className="text-gray-900 text-lg font-medium mb-2 text-center">{negocio.description}</h3>
              </div>
            </div>
            
          )
        }
        )
        }
        
    
  </div>
  <div className='py-40'>
  </div>
  </>
    
  )
}

export default Section